### ISSUE TITLE
Missing links again :(

### ISSUE THREAD

**Issue by jyn514** [poliorcetics/cargo-intraconv#14]
This just happened after the changes for #13. `-` is before the change, `+` is after.

```
-//! [`Layer` type]: Layer
-//! [`Layer` trait]: super::layer::Layer
+//! [`Layer` type]: struct.Layer.html
+//! [`Layer` trait]: ../layer/trait.Layer.html
```

**Comment by poliorcetics** [comment]
Yep, I saw it while writing more tests, could you check with the most recent commit ?

I think I fixed it in [`c9b704a`](https://github.com/poliorcetics/cargo-intraconv/commit/c9b704aa21a0f01ac5e8e6e14c82473f15a4bab5)

**Comment by jyn514** [comment]
Still doesn't work with that commit unfortunately. I'm on 370edada00a704b2d4fe8fa587afb178ce54bc37.

**Comment by poliorcetics** [comment]
Ok, I'll try to find it and fix it quickly, sorry for breaking your workflow so often !

**Comment by jyn514** [comment]
I don't know if _workflow_ is the right word, I'm testing it out as much as you are :P

**Comment by poliorcetics** [comment]
I'm testing with this file:

```rust
/// [`Layer` type]: struct.Layer.html
/// [`Layer` trait]: ../layer/trait.Layer.html
fn main() {
    //! [`Layer` type]: struct.Layer.html
    //! [`Layer` trait]: ../layer/trait.Layer.html
    println!("playground");
    println!("==========");
}
```

And I get the correct transformations:

<img width="488" alt="Screenshot 2020-10-08 at 01 04 04" src="https://user-images.githubusercontent.com/7951708/95396859-2af1b400-0902-11eb-8c2e-db1d07ef26c0.png">

I tried with `-a` and it works too.

I'm thinking this is maybe because I'm on macOS and you're on something else ?

**Comment by jyn514** [comment]
Hmm, let me try to put together an MCVE. I wouldn't expect it to be platform related.

**Comment by jyn514** [comment]
Oh I'm dumb - the command I was using was `for crate in tracing-*; do cargo-intraconv $crate/**/*.rs -a -c $(echo $crate | tr - _) 2>&1; done | less -R` and I exited out of `less` before it had time to run 😆 intraconv works fine.
